package de.tum.in.ase.insertteamnamehere.model;

public enum RestaurantType {
    ITALIAN, GERMAN, CHINESE, INDIAN, JAPANESE, GREEK, THAI, TURKISH, MEXICAN,
    BAR_RESTAURANT, CAFE, VEGETARIAN, BURGER, PIZZA, SUSHI_BAR, NOODLE_BAR, VIETNAMESE
}
